# TO CREATE ENVIRONMENT: conda env create -f new-wt.yml
# TO ACTIVATE: conda activate new-wt
# TO DEACTIVATE: conda deactivate
# TO DESTROY THE ENVIRONMENT: conda remove --name new-wt --all
#
name: new-wt
dependencies:
  - python=3.9.5
  - pip=21.1.2
  - pip:
    - sentence-transformers==1.2.1
    - torch==1.9.0
    - transformers==4.8.1
    - pytorch-lightning==1.3.7.post0
    - pandas==1.2.5
    - unidecode==1.2.0
    - spacy==3.0.6
